1 oc html css part 2
Akilai-lab/achiev-formation pull request #3
Opened 2020-01-12 22:09 UTC by Akilai-lab

2020-01-13 07:53 UTC, mel-mouk reviewed
Pour ajouter la font Nobile, ce que tu fais la ne fonctionne pas. Tu peux le tester en ouvrant ton fichier dans un navigateur puis en cliquant sur :
- Inspecter l'element
- Tu clic sur un h2 par exemple
- Tu desactives la regle "font-family: 'Nobile'" 
Tu verras que rien ne change

( Pour apprendre a utiliser l'outil inspecter l'element https://www.google.com/search?client=safari&rls=en&q=utiliser+inspecter+l%27element&ie=UTF-8&oe=UTF-8, https://developer.mozilla.org/fr/docs/Outils/Inspecteur/Comment/Examiner_et_éditer_le_code_HTML, https://fr.wikihow.com/inspecter-un-élément-sur-Google-Chrome )


Pour comprendre le fonctionnement des fonts personnalisées, regarde cet article : https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp 
Dit moi si des points ne sont pas clair. Et attention, dans tes src, que ce soit pour une image, une font, un autre fichier ..etc toujours mettre le path, le code ne peux pas deviner ou se trouve le fichier

D'autres liens interessants : 
https://css-tricks.com/snippets/css/using-font-face/
https://www.456bereastreet.com/archive/201012/font-face_tip_define_font-weight_and_font-style_to_keep_your_css_simple/

Attention aussi ton image de fond ne se répète pas et du coup laisse du blanc sur le coté quand on met la fenêtre en grand, ce serait plus propre si elle recouvrait tout

2020-01-13 08:37 UTC, Akilai-lab commented
Problème résolu avec le commit 1d22d8e.
je te laisse regarder

2020-01-15 09:17 UTC, mel-mouk requested changes
Je te laisse corriger ces points, ensuite je t'expliquerai comment mettre a jour ta branche 3 pour prendre en compte les corrections faites ici et je te ferai une review de la partie 3

2020-01-15 09:17 UTC, mel-mouk commented on 1-oc-html-css/index.css
> +@font-face
Attention a declarer la font-face avant de l'utiliser ( donc avant ton `h2, p, ul ...` )

2020-01-15 09:17 UTC, mel-mouk commented on 1-oc-html-css/index.css
> +	src: url(./assets/Nobile.ttf);
`./assets/Nobile.ttf` n'existed pas ;) Fais attention a tes chemins, la tes fichiers de fonts sont dans `assets/Nobile/...`. Essaye de modifier en ajoutant `Nobile-Regular.ttf` en tant que fichier pour Nobile par default, et `Nobile-Bold.ttf` pour la `font-weight` `bold` s'il te plait comme ca je valide que tu as bien compris les explications sur les font-face de la documentation que je t'ai envoyé

2020-01-15 09:17 UTC, mel-mouk commented on 1-oc-html-css/index.css
> +	background-repeat: no-repeat;
Le background ne se répète toujours pas, si tu ouvres ta fenêtre en grand tout le coté droit de l'écran a encore un fond blanc, regarde https://www.w3schools.com/css/css_background.asp

2020-01-16 19:32 UTC, Akilai-lab commented
j'ai modifié ce que tu m'as dit est-ce que cette fois c'est bon? pour la police quand j'ouvre le fichier html cela fonctionne

2020-01-18 17:11 UTC, Akilai-lab commented
j'ai modifié en suivant tes instructions

2020-01-19 08:22 UTC, Akilai-lab commented
ajout font-family au css bold

2020-01-19 17:14 UTC, merged