2 achiev landing 1
Akilai-lab/achiev-formation pull request #7
Opened 2020-01-31 15:28 UTC by Akilai-lab

2020-02-01 08:59 UTC, Akilai-lab commented
pull

2020-02-01 23:15 UTC, Akilai-lab commented
responsive jusque là où j'ai modifié les pages css et html

2020-02-06 16:34 UTC, Akilai-lab commented
.

2020-02-06 17:25 UTC, Akilai-lab commented
terminé!!! :D

2020-02-07 11:00 UTC, Akilai-lab commented
indentation, div en anglais, kebab case

2020-02-07 11:40 UTC, Akilai-lab commented
font family, et valeurs propriétés/défaut

2020-02-07 17:38 UTC, Akilai-lab commented
ajout font

2020-02-08 18:05 UTC, Akilai-lab commented
rectifs

2020-02-09 11:57 UTC, mel-mouk requested changes

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +
Il me semble que tout les `width: auto` la ne servent a rien, dans quel but tu as mis ça ?

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Pas besoin de préciser `font-stretch: normal`, `font-style: normal` ...etc c'est la propriété par default donc les mettre ne change rien. Autant garder ton code propre et clair en ne mettant que ce qui a un rôle

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
( Si tu vois ces propriété sur Zeplin, c'est parce que c'est un truc automatique qui génère un peu tout et n'importe quoi, il faut s'en inspirer pas le copier )

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +.box-img
Sur toute cette partie la, il te manque le layout gris. Je te conseille plutôt de garder ton `box-img` avec son `height: 400px` et de mettre l'image en background image, centrée et avec cover comme taille, comme ca tu sais que ca s'adaptera peu importe ton écran. Et du coup tu pourra rajouter le layout dedans qui as `background-color: rgba(74, 74, 74, 0.5)` pour faire l'effet de layout gris sur l'image.

attention en mobile ce bloc doit être plus grand ( Disons 475px )

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Cette façon de centrer le titre n'est pas correct, ca peut passer mais c'est beaucoup trop compliqué et pas assez précis.
Quand tu veux centrer en horizonta, tu peux utiliser `text-align: center`. en l'occurence, tu connais la hauteur du bloc, tu peux donc mettre un `top` et le `text-align: center`

Si tu ne veux pas t'embêter avec les calculs de taille ( ce qui est mieux ), tu peux aussi mettre le div qui sert de layout en `display: flex` avec align-item et justify-content center. Comme ca en mettant le h1 dedans, il sera toujours centré horizontalement et verticalement

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Ce bloc la n'est pas tout a fait bon non plus, tu met une width de 150px et un left de 45%, ce qui veux dire que c'est centré uniquement si 5% = 75px. Le border-radius également, comment as tu choisit 130px ?

Je te conseillerai d'utiliser un border-radius a 50% vu que tu veux un cercle. Pour centrer l'element, soit utilises les propriété flex du parent pour qu'il se place au milieu, soit tu dois faire un calcul plus precis pour le left ( `calc(50% - 75px)`

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
En responsive tu va surement devoir modifier la taille du parents souvent dans ce type de situation, du coup je te conseillerai de mettre la taille de l'image en % pour que modifier le parent modifie la taille de l'image sans effort de ta part.
Pour centrer l'element encore une fois, ce type de margin top/left en % sans prendre en compte les taille des elements ne sont pas assez precise, passe le parent en display flex et utilise ces propriété la pour le centrer, c'est pour ca que je t'ai fait faire les jeux sur les Flexbox

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	width: 357px;
Pareil pour le positionnement, la ca ne fonctionne pas sur toutes les tailles d'écran, c'est beaucoup trop precis. Ne met pas de with et utilise un text-align: center

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Je ne comprend pas le role de ce bloc. Pourquoi cette width et pourquoi ce padding ?

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	height: 120px;
Ne met pas de height sur les blocs de texte, il y a un flow naturel de lia page, ils prendront la place dont ils ont besoins, sur certaines tailles d'écrans tes paragraphes se superposent sinon. Pense bien a teste avec plein de taille de fenêtre différentes

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	height: 433px;
Ne met pas de height precise, joue avec le flow naturel de la page, les padding ..etc

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Meme retours que sur les blocs precedent, centre avec text-align center ou avec les Flexbox, pas assez precis de cette façon. Ne met pas de height et de width precise ca n'as pas d'intérêt sur ce bloc

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Meme retour que sur les blocs precedents

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	justify-content: space-evenly;
Sur les mock up tu remarqueras qu'il y a un certain alignement a gauche et a droite qui est coherent entre tout les blocs. Dans cet esprit, utilise plutôt space-between afin que le premier et derniers blocs soient bien au bord, et n'oublie pas les padding right/left ( Pas que sur ce bloc pour les padding d'ailleurs )

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Essaye de regrouper les propriétés qui vont ensemble, globalement c'est ca mais meme retour que le reste pour la façon de centrer

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
( Par regrouper j'entend ne pas avoir deux blocs .way-to )

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Meme retours que precedement

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Meme retours que precedement

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +
Fait une classe pour tes inputs ou tu définis ce qu;ils ont en commun ( border radius, color ..etc ) puis une qui influe sur la taille Plutot que de répéter les propriétés deux fois. Dans ce bloc attention au padding et a la responsive qui ne fonctionne pas actuellement

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +.final-frame
Tu n'as pas besoin d'autant d'elements html, fait simplement ton `<footer>` avec un `p` dedans. Pour le positionnement utilise les flex et le padding

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +			<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
C'est bien pour ca, maintenant si tu regarde bien tu utilises des weight qui ne sont pas importés ;) Retourne sur le site Google Font, et dans customize coche tout ce dont tu as besoin

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +				<div class="box">
Attention a l'indentation

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +				<h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
Attention a l'indentation Comme indiqué dans le css je te conseille d'organiser ca autrement avec l'image en background, un layout et le h1 dedans

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +					<h2>Qui sommes nous?</h2>
Attention a l'indentation

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +					<div class="text">
Tu n'as pas besoin d'autant de html, met juste ton bloc `who` ou `about-us` ou peu importe ( a la place de part1 ), et dedans met ton h2 et tes p, en l'occurence tu n'as pas besoin de plus

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +			<div id="part2">
Attention a l'indentation

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +			<div id="part2">
Essaye aussi de mettre un id plus clair que part2, quelqu'un qui n'as jamais vu ni les maquettes ni le rendu du site doit se retrouver très rapidement dans ton code

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +					<p>Voir plus</p>
Meme si pour l'instant il n'y a pas de lien et qu'un p est donc totalement valide, a long terme on se doute bien que ce sera cliquable, met un lien plutôt qu'un p du coup

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +				<div class="frame-small">
Meme si actuellement ils ne sont pas fonctionnel, on est sur un formulaire, utilise des inputs a la place des `frame-small`, ( regarde form, input et textarea )

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +				<div class="name">
Ne met pas une classe par champs, il y a d'autre propriétés pour ca ( name dans input ), les classes doivent avoir un role d'affichage, la elles ne servent a rien. Egalement ne me pet un p, mais utilise des label. 

Et tu peux simplifier ton html, si tu veux mettre des divs pour chaque partie alors ce qu'il faudrai faire pour les séparer logiquement serait d'avoir :
- div
   - label
   - input
- div 
   - label
   - input
...etc 

Mais avoir simplement un div autour du label n'est pas très utile

2020-02-09 11:57 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.html
> +			<footer>
Attention a l'indentation
Pas besoin d'autant de bloc ( footer, div#footer ..etc )
Met simplement un <footer> et un <p> dedans

2020-02-10 19:54 UTC, Akilai-lab commented
rectifs faites

2020-02-12 21:17 UTC, mel-mouk requested changes

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	background-position: center;
Ajoutes un `background-size: cover`, l'image s'adaptera mieux aux différentes largeurs

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +
Essayes de ne pas trop laisser de lignes vide comme ça ou celles après le bloc "section", une centre chaque bloc c'est bien

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	width: 100%;
Il prend 100% par default tu n'as pas forcement besoin de le préciser

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	width: 100%;
Il prend 100% par default tu n'as pas forcement besoin de le préciser

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	height: 400px;
Mets plutôt `height: 100%` comme ca il s'adapte a son parent tu n'as pas besoin de repréciser la taille a chaque fois vu que tu la fixe deja dans #box-img

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
Attention, le titre touche les bords selon la taille d'écran. Essayes de toujours respecter une certaine logique avec le padding ( selon les maquettes la logique n'est pas toujours la même ). La il y a globalement un padding de 50px sur les bords droites et gauche sur tout la page, donc le layout du header devrait l'avoir aussi pour que le titre n'aille jamais sur cette zone
En mobile le padding est de 25px sur les maquettes

Pour le titre ( donc le layout ) tu peux meme mettre le double sur chacun pour moins large que le reste de la page encore

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +.round
Attention tu as 2 blocs round

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +	border-radius: 75px / 75px;
Mets border-radius a 50% stp, comme ca si on veux changer la taille du header un jour, on a moins pas besoin d'adapter cette ligne

2020-02-12 21:17 UTC, mel-mouk commented on 2-achiev-landing/landing-v1.css
> +{
tu n'as pas traité ce point

2020-02-16 16:29 UTC, Akilai-lab commented
alors j'ai fait les recifs, cependant, je n'arrive pas  inverser le triangle avec le lien "voir plus" en utilisant column-reverse, surement parce que le lien est compris dans .way-to et non dans une nouvelle classe, mais ca marchait bien avant et je n'arrive pas à regler le soucis. Et j'ai utiliser #title forme pour adapter les cases du formulaire, mais seulement la 3eme est prise en compte, même si ca englobe tous les p du formulaire.

2020-02-16 16:40 UTC, Akilai-lab commented
c'est bon j'ai trouvé pour les cadres de formulaire en fait

2020-02-16 17:15 UTC, Akilai-lab commented
je te laisserai vérifier ca aussi si c'est bien ou non.

2020-02-17 17:27 UTC, Akilai-lab commented
h1, voir plus, inputs et nous contacter ok

2020-02-17 17:35 UTC, Akilai-lab commented
padding containers

2020-02-17 17:42 UTC, Akilai-lab commented
nos realisations space between et padding

2020-02-17 17:49 UTC, Akilai-lab commented
outline d'inputs

2020-02-17 17:55 UTC, Akilai-lab commented
police, bold, regular en 300 et 600

2020-02-17 18:02 UTC, Akilai-lab commented
font size rectifié

2020-02-17 19:30 UTC, Akilai-lab commented
responsiv ok.

2020-02-23 08:46 UTC, Akilai-lab commented
alors je bloque sur l'alignement des blocs, j'ai bien noté un padding left et right de 25px, mais ca reste toujours décalé sur la gauche et la droite a beaucoup d'espace.
j'ai regardé la taille de l'article et de la div mais rien ne bloque là dessus, aucun margin ou padding qui pourrait en être la cause.
j'ai tenté align items mais ca n'a aucun effet.

2020-02-23 08:59 UTC, Akilai-lab commented
et pour la flêche, il faut que j'y mette e margin left ou autrement?

2020-02-29 23:30 UTC, merged